# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GarbageClassification(object):
    def setupUi(self, GarbageClassification):
        GarbageClassification.setObjectName("GarbageClassification")
        GarbageClassification.resize(823, 381)
        GarbageClassification.setStyleSheet("background-color: rgb(36, 36, 54);")
        self.centralwidget = QtWidgets.QWidget(GarbageClassification)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 280, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 371, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(420, 170, 341, 41))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 140, 151, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 371, 241))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"image: url(:/resim/xlarge_icons_image_photo_3885.ico);")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(420, 80, 381, 23))
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 10)
        self.progressBar.setObjectName("progressBar")
        GarbageClassification.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GarbageClassification)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
        self.menubar.setObjectName("menubar")
        GarbageClassification.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GarbageClassification)
        self.statusbar.setObjectName("statusbar")
        GarbageClassification.setStatusBar(self.statusbar)

        self.retranslateUi(GarbageClassification)
        QtCore.QMetaObject.connectSlotsByName(GarbageClassification)

    def retranslateUi(self, GarbageClassification):
        _translate = QtCore.QCoreApplication.translate
        GarbageClassification.setWindowTitle(_translate("GarbageClassification", "Garbage Classification"))
        self.pushButton.setText(_translate("GarbageClassification", "Analyze"))
        self.label.setText(_translate("GarbageClassification", "*drag the image here"))
        self.label_2.setText(_translate("GarbageClassification", "Predicted class: "))
import image_rc
